# Generated by Django 4.2.30 on 2026-04-10 11:18

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('gcs_uri', models.CharField(blank=True, help_text='Google Cloud Storage URI (gs://bucket/path)', max_length=1024, null=True, validators=[core.validators.validate_gcs_uri])),
                ('total_duration', models.FloatField(blank=True, help_text='Total duration in seconds', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_source', models.BooleanField(default=False, help_text='True if this is official/source content, False if suspect')),
                ('processing_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Awaiting_AI_Review', 'Awaiting AI Review'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='core.organization')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PiracyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_suspect_url', models.CharField(help_text='Original URL where the suspect content was found', max_length=2048)),
                ('match_confidence', models.FloatField(help_text='Cosine similarity match confidence (0.0 to 1.0)')),
                ('gemini_reasoning', models.JSONField(blank=True, help_text='Structured reasoning output from Gemini 1.5 Pro', null=True)),
                ('is_fair_use', models.BooleanField(default=False, help_text='Whether Gemini determined this is fair use')),
                ('dmca_draft', models.TextField(blank=True, help_text='AI-generated DMCA takedown notice draft', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Takedown_Drafted', 'Takedown Drafted'), ('Takedown_Sent', 'Takedown Sent'), ('Dismissed', 'Dismissed')], db_index=True, default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_video', models.ForeignKey(limit_choices_to={'is_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='source_reports', to='core.videoasset')),
                ('suspect_video', models.ForeignKey(limit_choices_to={'is_source': False}, on_delete=django.db.models.deletion.CASCADE, related_name='suspect_reports', to='core.videoasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Segment start time in seconds')),
                ('end_time', models.FloatField(help_text='Segment end time in seconds')),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=1408)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='core.videoasset')),
            ],
            options={
                'ordering': ['video_asset', 'start_time'],
                'unique_together': {('video_asset', 'start_time')},
            },
        ),
    ]
