# Generated by Django 4.2.30 on 2026-04-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piracyreport',
            name='matched_segment_end',
            field=models.FloatField(blank=True, help_text='End time (in seconds) of the highest match confidence segment', null=True),
        ),
        migrations.AddField(
            model_name='piracyreport',
            name='matched_segment_start',
            field=models.FloatField(blank=True, help_text='Start time (in seconds) of the highest match confidence segment', null=True),
        ),
    ]
